{% set name = "PyKrige" %}
{% set version = "1.6.1" %}
{% set sha256 = "7432287306d13820ed0f0ec2f52c12fa462e18015abbf8fa627beab989ccaff6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script:
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - toml
    - setuptools >=45
    - setuptools_scm >=3.5
    - cython >=0.28.3, <3.0
    - numpy >=1.14.5, <2.0
    - scipy >=1.1.0, <2.0
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('scipy') }}

test:
  imports:
    - pykrige
  requires:
    - pytest >=5.3.0
    - scikit-learn >=0.19
    - gstools >=1.1.1, <2.0
  source_files:
    - tests
  commands:
    - pytest -vv tests

about:
  home: https://github.com/GeoStat-Framework/PyKrige
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Kriging Toolkit for Python
  description: |
    The code supports two- and three- dimensional ordinary and universal
    kriging. Standard variogram models (linear, power, spherical,
    gaussian, exponential) are built in, but custom variogram models
    can also be used with the code.
  doc_url: http://pykrige.readthedocs.io/
  dev_url: https://github.com/GeoStat-Framework/PyKrige

extra:
  recipe-maintainers:
    - rth
    - MuellerSeb
