travis:
  secure:
    BINSTAR_TOKEN: Uuo83xXgnfIkhCm107geKTO7ApiubGD0qecofAHlzS1+34tLSosXsKvDS0zd7k8NA3WEwsRdsKT17fjq1ugHmHkQH7xco5SiDOwG/t7frHX0Ysfy8K1PbtmSKKel1q411CDUZIRPvYXUMPobW6pwBAunq1OMtTgI/u9hLZbL8+HS/uQHGboscWDSQUzV4MMPcUtqtPsJydze/jtvMTBGpTJtEQk3ieRtKHAJszpKJUUPMpN+u1aK+v3u/kLf7A4h1bwBOtXR0pc+6c2v6U/IjBj+6qWRZJ6ix4ZqV9fkGVyHtY6zMsiRkFFvciYixBzPlAVhJc6WqrXUuAU7AFLLcKP8ffAk4tpCjEVlm5WaW+KJn5H4iFnYKS1KStsMj70oBsGR7jps3XnSCTMvAeRAUGF2KQdKMK8foB2Esqpm4mGp4cJ8BNjPdIimWQXsygt8pCF2zRCHdzqYKz/RRWP6F+OSJJpbcO96ul39XjFCV3O5nEK1zREElfvIC2zrZGpxBv5Mam3VVNp8Ecjj8tvwn8S9aW4ptwfqNVgsyqnAmb2krsO49iu8IxEhPJdbsGfEyGzVIZaQSyvIgXcGtAGaQbqRNc14GMSrdOPO5SzkWnUYG/WgFdbIqAvcZc6bxreFsDKV73wgEqqlJobru/Xvjkk7Vo/l/w83jPdRVVssm8o=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
