travis:
  secure:
    BINSTAR_TOKEN: CLIDukZ/bAbRsoF+TuPWmM82Q2XtbfPbvRAqA1InNtoxfkAThTzLa9kXmU/uYn/FWFTKIDD2T7ICE6TtjhPLqIoQcpU223rIJpCguIkHFLuXNGlJdVxaExmwhPOT+xcbshyqEGox2DaSapdyBKkqxKHimTN9QMW6L/PIQr2orYluB9xISc0cxjVOWxVjx9XW6o5N6pRQWgz+IUqNKzl6vseZOEgRfweQaswafOZMoblaQer8EhAxXZGXW1OOaOtJgBBuSwUkvp450s4V3L3mJOZxD2J+jPZYf+9BJ4EExYWO0PNuOROSHcD3YaeF5GGo6PCvU7lwXBElpP5m9oIhdT9Xce+XI0+rGqwxMXDXRotsFRmCMaDAjhfFBGgmc3jD20Hm6SisZps3THXH1wv0wYqmR8/2q962ZzezxYEPPs7cWulqGViTWEsR5y4Ruu5PZGfZyTX7Miu5tyztGQ60zThnShU8HxIFMMNqRsPbSaC3tdniBBfJFlZ05S7Xt07/yK2JGl4WYGQImu0w39+oZITM6V5U1JJZCWpW33EpNVymA8eDKHLzv0H3bQhRBnGbekDdVjcSU5/Irv/R6eIUKB9a2DuK8hjEDI880QP3MMZEkASMaQ0dpkXoDWRGq22dxCPW3aSiCuGpMca7Sa61WJgQdu9SxXMjA3oO/AoZFoE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
