travis:
  secure:
    BINSTAR_TOKEN: OewgVktHzcaQGgGr17MPfjr2LejtEr7deqPDAFgW3RJqj1R6I/jGdGUTZ050fGoP4Nv8N5h8LFfNzxU9+5n+8oC4hE92mTgbCr/SGykVHn7OSM6BapMqryBly+Gda9OG9/xhzaCz774j0+6lMpwl8FtT8qpTXRwDLLVS2qRnpYqdj8MBR3N2TdG9mmUKB30CVsKmPijAbApspiC87uGMVLhtqUKLQlbiyUpFh3XKCP6w7XOp4fkr8r2zrxgrBX5j3/4YQdTeOB5eUcwjDje2rUG2lgyjEpuLzDHGW+WyTELiExHzcGBw3xGoeuXrC+nVvTmvC6T+vWrGN70327QdKPSvbFDa0RWzxs5VQMko/l7mHVrsRsOJOfZPXP4+lcSK4V9DbZUJrsQNVqWKcMnAqVcZoXjJX2hw2sIHwYDaimuniHIrZFFrmg4IZSWiLszsW+AV83KGngWxl3TCgdQUoWoK0zR2bkC74fv2u05ww7iGeuvoqeSsT8N88P3r5n+KRTDusVtxtxp0s8b9GXe+a65RUJX2Ng8TPgc4yE+wgI2NK4e3PSBOyZDpyZrdwLvXP6nx4ssWD9JLgRbfp9QLJxdiJUU+Vilq1xFNs4SxaZbME+1YE1FKVCZUEBxGZxMORW+7rnSIdgIrVEboLyxOohggMyAuES6K3g4BJco83zI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
